# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jasper/Documents/Schooljaar_2016-2017/Programmable_logic/vhdl_project/vhdl_project.srcs/sources_1/ip/dual_prt_ram_block_strg_1/dual_prt_ram_block_strg.xci
# IP: The module: 'dual_prt_ram_block_strg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jasper/Documents/Schooljaar_2016-2017/Programmable_logic/vhdl_project/vhdl_project.srcs/sources_1/ip/dual_prt_ram_block_strg_1/dual_prt_ram_block_strg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_prt_ram_block_strg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/jasper/Documents/Schooljaar_2016-2017/Programmable_logic/vhdl_project/vhdl_project.srcs/sources_1/ip/dual_prt_ram_block_strg_1/dual_prt_ram_block_strg.xci
# IP: The module: 'dual_prt_ram_block_strg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jasper/Documents/Schooljaar_2016-2017/Programmable_logic/vhdl_project/vhdl_project.srcs/sources_1/ip/dual_prt_ram_block_strg_1/dual_prt_ram_block_strg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_prt_ram_block_strg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
