set_property PACKAGE_PIN L16 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN R18 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

set_property PACKAGE_PIN M14 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN M15 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN G14 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN D18 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[3]}]

#pmod B
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property PACKAGE_PIN T20 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property PACKAGE_PIN Y18 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DCLK]
set_property PACKAGE_PIN Y19 [get_ports DCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property PACKAGE_PIN U20 [get_ports CS]
set_property IOSTANDARD LVCMOS33 [get_ports BUSY]
set_property PACKAGE_PIN W19 [get_ports BUSY]
set_property PACKAGE_PIN W18 [get_ports BL_EN]
set_property IOSTANDARD LVCMOS33 [get_ports BL_EN]
set_property PACKAGE_PIN V20 [get_ports GND]
set_property IOSTANDARD LVCMOS33 [get_ports GND]

#pmod C
set_property PACKAGE_PIN W14 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property PACKAGE_PIN V15 [get_ports {RED[1]}]
set_property PACKAGE_PIN Y14 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[2]}]
set_property PACKAGE_PIN W15 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[3]}]
set_property PACKAGE_PIN T12 [get_ports {RED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[4]}]
set_property PACKAGE_PIN T11 [get_ports {RED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[5]}]
set_property PACKAGE_PIN U12 [get_ports {RED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[6]}]
set_property PACKAGE_PIN T10 [get_ports {RED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[7]}]

#pmod D
set_property PACKAGE_PIN U14 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN T14 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN U15 [get_ports {GREEN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[4]}]
set_property PACKAGE_PIN T15 [get_ports {GREEN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[5]}]
set_property PACKAGE_PIN V17 [get_ports {GREEN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[6]}]
set_property PACKAGE_PIN P14 [get_ports {GREEN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[7]}]
set_property PACKAGE_PIN V18 [get_ports {BLUE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN R14 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[1]}]

#pmod E
set_property PACKAGE_PIN V13 [get_ports {BLUE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[4]}]
set_property PACKAGE_PIN V12 [get_ports {BLUE[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[5]}]
set_property PACKAGE_PIN U17 [get_ports {BLUE[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[6]}]
set_property PACKAGE_PIN W16 [get_ports {BLUE[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[7]}]
set_property PACKAGE_PIN T17 [get_ports P_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports P_CLK]
set_property PACKAGE_PIN J15 [get_ports DISP_EN]
set_property IOSTANDARD LVCMOS33 [get_ports DISP_EN]
set_property PACKAGE_PIN Y17 [get_ports H_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports H_SYNC]
set_property PACKAGE_PIN H15 [get_ports V_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports V_SYNC]

set_property MARK_DEBUG true [get_nets {X_POS[1]}]
set_property MARK_DEBUG true [get_nets {X_POS[2]}]
set_property MARK_DEBUG true [get_nets {X_POS[3]}]
set_property MARK_DEBUG true [get_nets {X_POS[4]}]
set_property MARK_DEBUG true [get_nets {X_POS[5]}]
set_property MARK_DEBUG true [get_nets {X_POS[6]}]
set_property MARK_DEBUG true [get_nets {X_POS[7]}]
set_property MARK_DEBUG true [get_nets {X_POS[8]}]
set_property MARK_DEBUG true [get_nets {X_POS[9]}]
set_property MARK_DEBUG true [get_nets {Y_POS[0]}]
set_property MARK_DEBUG true [get_nets {Y_POS[1]}]
set_property MARK_DEBUG true [get_nets {Y_POS[2]}]
set_property MARK_DEBUG true [get_nets {Y_POS[3]}]
set_property MARK_DEBUG true [get_nets {Y_POS[4]}]
set_property MARK_DEBUG true [get_nets {Y_POS[5]}]
set_property MARK_DEBUG true [get_nets {Y_POS[6]}]
set_property MARK_DEBUG true [get_nets {Y_POS[7]}]
set_property MARK_DEBUG true [get_nets {Y_POS[8]}]
set_property MARK_DEBUG true [get_nets {Y_POS[9]}]